<?php
require '/wordpress/wp-load.php';
update_option( 'realestate_platform_settings_general', array( 'operating_mode' => 'standalone' ) );
$bootstrap = \Mayfair\RealEstatePlatform\Core\Bootstrap::instance();
$bootstrap->services()->get( 'content' )->initialize();
do_action( 'rest_api_init' );
$user_a = wp_create_user( 'contract-a', 'pass', 'contract-a@example.test' );
$user_b = wp_create_user( 'contract-b', 'pass', 'contract-b@example.test' );
$property = wp_insert_post( array( 'post_type' => 'property', 'post_status' => 'publish', 'post_title' => '<script>x</script> Safe' ) );
$checks = array( 'rest' => array(), 'ajax' => array(), 'privacy' => array(), 'diagnostics' => array(), 'security' => array(), 'integrity' => array() );
function request( string $method, string $route, array $params = array() ): \WP_REST_Response {
	$request = new \WP_REST_Request( $method, $route );
	foreach ( $params as $key => $value ) { $request->set_param( $key, $value ); }
	return rest_do_request( $request );
}
function good( \WP_REST_Response $response ): bool { return $response->get_status() >= 200 && $response->get_status() < 300; }
function bad( \WP_REST_Response $response ): bool { return $response->get_status() >= 400 && $response->get_status() < 500 && is_array( $response->get_data() ) && isset( $response->get_data()['code'] ); }
wp_set_current_user( 0 );
$checks['rest']['anonymous_blocked'] = bad( request( 'GET', '/realestate-platform/v1/me/favorites' ) );
wp_set_current_user( $user_a );
$before_post = serialize( array( get_post( $property ), get_post_meta( $property ) ) );
$add = request( 'POST', "/realestate-platform/v1/me/favorites/$property" );
$checks['rest']['favorite_add'] = good( $add );
$checks['rest']['favorite_duplicate'] = good( request( 'POST', "/realestate-platform/v1/me/favorites/$property" ) );
$checks['rest']['favorite_status'] = true === request( 'GET', "/realestate-platform/v1/me/favorites/$property" )->get_data()['favorite'];
$checks['rest']['favorite_list'] = good( request( 'GET', '/realestate-platform/v1/me/favorites', array( 'page' => 1, 'per_page' => 20 ) ) );
foreach ( array( 0, -1, 'abc', array(), null ) as $value ) { $checks['rest']['favorite_invalid_' . md5( serialize( $value ) )] = bad( request( 'POST', '/realestate-platform/v1/me/favorites/0', array( 'id' => $value ) ) ); }
$checks['rest']['pagination_zero'] = bad( request( 'GET', '/realestate-platform/v1/me/favorites', array( 'page' => 0 ) ) );
$checks['rest']['pagination_text'] = bad( request( 'GET', '/realestate-platform/v1/me/favorites', array( 'page' => 'abc' ) ) );
$compare = request( 'GET', '/realestate-platform/v1/compare', array( 'ids' => array( $property ) ) );
$checks['rest']['compare_valid'] = good( $compare ) && ! str_contains( $compare->get_data()[0]['title'], '<' ) && array_keys( $compare->get_data()[0] ) === array( 'id', 'title', 'url', 'price', 'currency', 'city', 'area', 'bedrooms', 'bathrooms' );
$checks['rest']['compare_string'] = bad( request( 'GET', '/realestate-platform/v1/compare', array( 'ids' => '1,2' ) ) );
$checks['rest']['compare_five'] = bad( request( 'GET', '/realestate-platform/v1/compare', array( 'ids' => array( 1, 2, 3, 4, 5 ) ) ) );
$checks['rest']['compare_bad_id'] = bad( request( 'GET', '/realestate-platform/v1/compare', array( 'ids' => array( 'abc' ) ) ) );
$create = request( 'POST', '/realestate-platform/v1/me/saved-searches', array( 'title' => 'Delhi', 'criteria' => array( 'city' => 'Delhi' ) ) );
$saved = $create->get_data();
$checks['rest']['saved_create'] = good( $create ) && isset( $saved['id'] );
$checks['rest']['saved_list'] = good( request( 'GET', '/realestate-platform/v1/me/saved-searches' ) );
$checks['rest']['saved_get'] = good( request( 'GET', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] ) );
$checks['rest']['saved_bad_criteria'] = bad( request( 'POST', '/realestate-platform/v1/me/saved-searches', array( 'title' => 'x', 'criteria' => 'string' ) ) );
$checks['rest']['saved_update_bad_bool'] = bad( request( 'PUT', '/realestate-platform/v1/me/saved-searches/' . $saved['id'], array( 'id' => $saved['id'], 'title' => 'x', 'criteria' => array(), 'enabled' => 'banana' ) ) );
$update = request( 'PUT', '/realestate-platform/v1/me/saved-searches/' . $saved['id'], array( 'id' => $saved['id'], 'title' => 'Delhi 2', 'criteria' => array( 'city' => 'Delhi' ), 'enabled' => false ) );
$checks['rest']['saved_update'] = good( $update ) && false === $update->get_data()['enabled'];
$alert = request( 'POST', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] . '/alert', array( 'id' => $saved['id'], 'frequency' => 'daily', 'enabled' => true ) );
$alert_data = $alert->get_data();
$checks['rest']['alert_save'] = good( $alert ) && isset( $alert_data['id'] );
$checks['rest']['alert_get'] = good( request( 'GET', '/realestate-platform/v1/me/alerts/' . $alert_data['id'] ) );
$checks['rest']['alert_frequency'] = bad( request( 'POST', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] . '/alert', array( 'id' => $saved['id'], 'frequency' => 'hourly', 'enabled' => true ) ) );
$checks['rest']['alert_bad_bool'] = bad( request( 'POST', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] . '/alert', array( 'id' => $saved['id'], 'frequency' => 'daily', 'enabled' => 'banana' ) ) );
wp_set_current_user( $user_b );
$checks['security']['saved_get_idor'] = bad( request( 'GET', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] ) );
$checks['security']['saved_delete_idor'] = bad( request( 'DELETE', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] ) );
$checks['security']['alert_get_idor'] = bad( request( 'GET', '/realestate-platform/v1/me/alerts/' . $alert_data['id'] ) );
$checks['security']['alert_delete_idor'] = bad( request( 'DELETE', '/realestate-platform/v1/me/alerts/' . $alert_data['id'] ) );
$checks['security']['alert_modify_idor'] = bad( request( 'POST', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] . '/alert', array( 'id' => $saved['id'], 'frequency' => 'weekly', 'enabled' => true ) ) );
wp_set_current_user( $user_a );
$disable = request( 'POST', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] . '/alert', array( 'id' => $saved['id'], 'frequency' => 'daily', 'enabled' => false ) );
$checks['rest']['alert_disable'] = good( $disable ) && false === $disable->get_data()['enabled'];
$checks['rest']['alert_reenable'] = good( request( 'POST', '/realestate-platform/v1/me/saved-searches/' . $saved['id'] . '/alert', array( 'id' => $saved['id'], 'frequency' => 'weekly', 'enabled' => true ) ) );
$temp = request( 'POST', '/realestate-platform/v1/me/saved-searches', array( 'title' => 'Temporary', 'criteria' => array( 'city' => 'Pune' ) ) )->get_data();
$checks['rest']['saved_delete'] = good( request( 'DELETE', '/realestate-platform/v1/me/saved-searches/' . $temp['id'] ) );
$ajax = new \Mayfair\RealEstatePlatform\UserFeatures\UserFeaturesAjaxController( $bootstrap->services()->get( 'favorites' ), $bootstrap->services()->get( 'saved_searches' ), $bootstrap->services()->get( 'alerts' ), new \Mayfair\RealEstatePlatform\UserFeatures\MutationRateLimiter() );
$nonce = wp_create_nonce( $ajax::NONCE_ACTION );
$checks['ajax']['missing_nonce'] = is_wp_error( $ajax->process( array() ) );
$checks['ajax']['invalid_nonce'] = is_wp_error( $ajax->process( array( '_ajax_nonce' => 'bad' ) ) );
$checks['ajax']['bad_operation'] = is_wp_error( $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'bad' ) ) );
$checks['ajax']['bad_id'] = is_wp_error( $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'favorite_add', 'property_id' => 'banana' ) ) );
$checks['ajax']['bad_criteria'] = is_wp_error( $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'saved_create', 'title' => 'x', 'criteria' => 'bad' ) ) );
$checks['ajax']['bad_bool'] = is_wp_error( $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'alert_save', 'saved_search_id' => $saved['id'], 'frequency' => 'daily', 'enabled' => 'banana' ) ) );
$checks['ajax']['valid_add'] = ! is_wp_error( $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'favorite_add', 'property_id' => $property ) ) );
$checks['ajax']['valid_remove'] = ! is_wp_error( $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'favorite_remove', 'property_id' => $property ) ) );
$checks['ajax']['valid_toggle'] = ! is_wp_error( $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'favorite_toggle', 'property_id' => $property ) ) );
$ajax_saved = $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'saved_create', 'title' => 'Ajax', 'criteria' => array( 'city' => 'Mumbai' ) ) );
$checks['ajax']['valid_saved_create'] = is_array( $ajax_saved ) && isset( $ajax_saved['id'] );
$ajax_alert = $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'alert_save', 'saved_search_id' => $ajax_saved['id'], 'frequency' => 'weekly', 'enabled' => true ) );
$checks['ajax']['valid_alert_save'] = is_array( $ajax_alert ) && isset( $ajax_alert['id'] );
$checks['ajax']['valid_alert_delete'] = true === $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'alert_delete', 'id' => $ajax_alert['id'] ) );
$checks['ajax']['valid_saved_delete'] = true === $ajax->process( array( '_ajax_nonce' => $nonce, 'operation' => 'saved_delete', 'id' => $ajax_saved['id'] ) );
$limiter = new \Mayfair\RealEstatePlatform\UserFeatures\MutationRateLimiter();
$checks['ajax']['rate_below'] = $limiter->allow( $user_a, 'contract-limit', 3 ) && $limiter->allow( $user_a, 'contract-limit', 3 );
$checks['ajax']['rate_threshold'] = $limiter->allow( $user_a, 'contract-limit', 3 );
$checks['ajax']['rate_exceeded'] = ! $limiter->allow( $user_a, 'contract-limit', 3 );
$checks['ajax']['rate_user_isolated'] = $limiter->allow( $user_b, 'contract-limit', 3 );
$checks['ajax']['rate_operation_isolated'] = $limiter->allow( $user_a, 'other-operation', 3 );
$privacy = new \Mayfair\RealEstatePlatform\Privacy\PrivacyFoundation();
$checks['privacy']['exporter_registered'] = isset( $privacy->exporters( array() )['realestate-platform-user-state'] );
$checks['privacy']['eraser_registered'] = isset( $privacy->erasers( array() )['realestate-platform-user-state'] );
$export = $privacy->export( 'contract-a@example.test' );
$checks['privacy']['export'] = $export['done'] && ! empty( $export['data'] );
$diagnostic = new \Mayfair\RealEstatePlatform\Diagnostics\UserFeaturesCheck();
$before_diag = serialize( array( $GLOBALS['wpdb']->get_results( 'SELECT * FROM ' . $GLOBALS['wpdb']->prefix . 'rep_saved_searches' ), $GLOBALS['wpdb']->get_results( 'SELECT * FROM ' . $GLOBALS['wpdb']->prefix . 'rep_search_alerts' ) ) );
$result = $diagnostic->run();
$after_diag = serialize( array( $GLOBALS['wpdb']->get_results( 'SELECT * FROM ' . $GLOBALS['wpdb']->prefix . 'rep_saved_searches' ), $GLOBALS['wpdb']->get_results( 'SELECT * FROM ' . $GLOBALS['wpdb']->prefix . 'rep_search_alerts' ) ) );
$checks['diagnostics']['healthy'] = 'PASS' === $result->status;
$checks['diagnostics']['read_only'] = $before_diag === $after_diag;
$GLOBALS['wpdb']->update( $GLOBALS['wpdb']->prefix . 'rep_saved_searches', array( 'criteria_json' => '{bad' ), array( 'id' => $saved['id'] ) );
$corrupt_before = $GLOBALS['wpdb']->get_var( $GLOBALS['wpdb']->prepare( 'SELECT criteria_json FROM ' . $GLOBALS['wpdb']->prefix . 'rep_saved_searches WHERE id=%d', $saved['id'] ) );
$corrupt_result = $diagnostic->run();
$corrupt_after = $GLOBALS['wpdb']->get_var( $GLOBALS['wpdb']->prepare( 'SELECT criteria_json FROM ' . $GLOBALS['wpdb']->prefix . 'rep_saved_searches WHERE id=%d', $saved['id'] ) );
$checks['diagnostics']['invalid_json_detected'] = 'FAIL' === $corrupt_result->status && 1 === $corrupt_result->details['invalid_saved_searches'];
$checks['diagnostics']['corruption_not_repaired'] = $corrupt_before === $corrupt_after;
$GLOBALS['wpdb']->update( $GLOBALS['wpdb']->prefix . 'rep_saved_searches', array( 'criteria_json' => wp_json_encode( array( 'city' => 'Delhi' ) ) ), array( 'id' => $saved['id'] ) );
$GLOBALS['wpdb']->update( $GLOBALS['wpdb']->prefix . 'rep_search_alerts', array( 'failure_count' => 1 ), array( 'id' => $alert_data['id'] ) );
$failed_result = $diagnostic->run();
$checks['diagnostics']['failed_alert_warn'] = 'WARN' === $failed_result->status && 1 === $failed_result->details['failed_alerts'];
$GLOBALS['wpdb']->update( $GLOBALS['wpdb']->prefix . 'rep_search_alerts', array( 'failure_count' => 0 ), array( 'id' => $alert_data['id'] ) );
$GLOBALS['wpdb']->insert( $GLOBALS['wpdb']->prefix . 'rep_favorites', array( 'user_id' => 999999, 'post_id' => $property, 'created_at' => current_time( 'mysql', true ) ) );
$checks['diagnostics']['orphan_favorite_detected'] = 'FAIL' === $diagnostic->run()->status;
$GLOBALS['wpdb']->delete( $GLOBALS['wpdb']->prefix . 'rep_favorites', array( 'user_id' => 999999 ) );
$GLOBALS['wpdb']->update( $GLOBALS['wpdb']->prefix . 'rep_search_alerts', array( 'saved_search_id' => 999999 ), array( 'id' => $alert_data['id'] ) );
$checks['diagnostics']['broken_alert_detected'] = 'FAIL' === $diagnostic->run()->status;
$GLOBALS['wpdb']->update( $GLOBALS['wpdb']->prefix . 'rep_search_alerts', array( 'saved_search_id' => $saved['id'] ), array( 'id' => $alert_data['id'] ) );
update_option( 'realestate_platform_db_version', '002' );
$checks['diagnostics']['schema_mismatch_detected'] = 'FAIL' === $diagnostic->run()->status;
update_option( 'realestate_platform_db_version', REALESTATE_PLATFORM_DB_VERSION );
wp_clear_scheduled_hook( \Mayfair\RealEstatePlatform\UserFeatures\AlertScheduler::HOOK );
$checks['diagnostics']['scheduler_missing_detected'] = 'WARN' === $diagnostic->run()->status;
$bootstrap->services()->get( 'alert_scheduler' )->register();
$checks['integrity']['property_unchanged'] = $before_post === serialize( array( get_post( $property ), get_post_meta( $property ) ) );
$checks['integrity']['saved_owner_intact'] = ! is_wp_error( $bootstrap->services()->get( 'saved_searches' )->get( $user_a, $saved['id'] ) );
$erase = $privacy->erase( 'contract-a@example.test' );
$checks['privacy']['erase'] = $erase['done'] && $erase['items_removed'];
$checks['integrity']['erased'] = 0 === (int) $GLOBALS['wpdb']->get_var( $GLOBALS['wpdb']->prepare( 'SELECT COUNT(*) FROM ' . $GLOBALS['wpdb']->prefix . 'rep_saved_searches WHERE user_id=%d', $user_a ) );
$flat = array(); foreach ( $checks as $section ) { $flat = array_merge( $flat, array_values( $section ) ); }
echo wp_json_encode( array( 'status' => in_array( false, $flat, true ) ? 'FAIL' : 'PASS', 'checks' => $checks ), JSON_PRETTY_PRINT );
