import {runCLI} from '@wp-playground/cli'; import fs from 'node:fs';
const c=await runCLI({command:'server',php:'8.3',wp:'6.4',mount:[{hostPath:'./plugins/realestate-platform',vfsPath:'/wordpress/wp-content/plugins/realestate-platform'}]});
const code=String.raw`<?php
define('WP_CLI',true); class WP_CLI {public static array $commands=[],$lines=[]; public static function add_command($n,$c){self::$commands[$n]=$c;} public static function line($s){self::$lines[]=$s;} public static function error($s){throw new RuntimeException($s);}}
require '/wordpress/wp-load.php'; require_once ABSPATH.'wp-admin/includes/plugin.php'; activate_plugin('realestate-platform/realestate-platform.php'); do_action('plugins_loaded'); do_action('init');
$cmds=WP_CLI::$commands; $checks=['registered_status'=>isset($cmds['realestate search-index status']),'registered_rebuild'=>isset($cmds['realestate search-index rebuild'])];
wp_set_current_user(1); $admin=get_role('administrator'); foreach(\Mayfair\RealEstatePlatform\Capabilities\CapabilityManager::CAPS as $cap){$admin->add_cap($cap);} $status=$cmds['realestate search-index status']; $rebuild=$cmds['realestate search-index rebuild'];
$before=get_option('realestate_platform_search_last_rebuild',null); $status(); $status_data=json_decode(end(WP_CLI::$lines),true); $checks['status_output']=is_array($status_data)&&array_key_exists('healthy',$status_data); $checks['status_read_only']=$before===get_option('realestate_platform_search_last_rebuild',null);
wp_set_current_user(0); try{$status();$checks['status_authorization']=false;}catch(Throwable $e){$checks['status_authorization']=str_contains($e->getMessage(),'not authorized');}
try{$rebuild([],[]);$checks['rebuild_authorization']=false;}catch(Throwable $e){$checks['rebuild_authorization']=str_contains($e->getMessage(),'not authorized');}
wp_set_current_user(1); $results=[]; foreach([0,10,100,1000] as $target){global$wpdb;$existing=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->posts} WHERE post_type='property' AND post_status='publish'");for($i=$existing;$i<$target;$i++){wp_insert_post(['post_type'=>'property','post_title'=>'CLI '.$i,'post_status'=>'publish']);} $rebuild([],['batch-size'=>37]);$x=json_decode(end(WP_CLI::$lines),true);global$wpdb;$count=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}rep_search_properties");$results[(string)$target]=['output'=>$x,'indexed'=>$count,'pass'=>$x['failed']===0&&$count===$target];}
$rebuild([],['batch-size'=>37]);$repeat=json_decode(end(WP_CLI::$lines),true);$checks['rebuild_sizes']=!in_array(false,array_column($results,'pass'),true);$checks['repeat']=$repeat['failed']===0;
try{$rebuild([],['batch-size'=>0]);$checks['failure_exit']=false;}catch(Throwable $e){$checks['failure_exit']=str_contains($e->getMessage(),'failed safely');}
echo wp_json_encode(['status'=>in_array(false,$checks,true)?'FAIL':'PASS','runtime'=>'WP-CLI command callbacks executed in a deterministic CLI-compatible harness; native wp-cli binary unavailable.','checks'=>$checks,'rebuilds'=>$results],JSON_PRETTY_PRINT);`;
const o=await c.playground.run({code});const t=new TextDecoder().decode(o.bytes),j=t.slice(t.indexOf('{'));fs.writeFileSync('verification-results/phase3-cli.json',j);console.log(j);await c[Symbol.asyncDispose]();if(JSON.parse(j).status!=='PASS')process.exitCode=1;
